### PR TITLE
Cr categories view

### PR DESCRIPTION
**Pull request by CheoR**
# Description

User can view categories alphabetically.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# Testing Instructions

`git fetch --all`
`git checkout cr-categories-view`
`npm start`

For server-side instructions, see backend pull request.

After the backend is up and running, in Postman, make a `GET` request to 

`http://localhost:8000/categories`

to view all categories. In browser, after successful login, click on `Category Management` to view a list of categories listed alphabetically.

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by phillip-phan-imprivata — COMMENTED** [review]
it works, but your provider uses "lu_token" instead of the "rare_user_id"

**Review by phillip-phan-imprivata — CHANGES_REQUESTED** [review]
it works, but your provider uses "lu_token" instead of the "rare_user_id"

**Review by notdanross — APPROVED** [review]
CATegories rendering!

**Review by phillip-phan-imprivata — APPROVED** [review]
good fix

**Pull request merged**
